// ISO 4217 active currencies — code, name, symbol
export const CURRENCIES = [
  ["USD","US Dollar","$"],["EUR","Euro","€"],["GBP","British Pound","£"],["JPY","Japanese Yen","¥"],
  ["PHP","Philippine Peso","₱"],["SAR","Saudi Riyal","﷼"],["AED","UAE Dirham","د.إ"],["AUD","Australian Dollar","A$"],
  ["CAD","Canadian Dollar","C$"],["CHF","Swiss Franc","Fr"],["CNY","Chinese Yuan","¥"],["HKD","Hong Kong Dollar","HK$"],
  ["SGD","Singapore Dollar","S$"],["NZD","New Zealand Dollar","NZ$"],["INR","Indian Rupee","₹"],["KRW","South Korean Won","₩"],
  ["TWD","New Taiwan Dollar","NT$"],["THB","Thai Baht","฿"],["MYR","Malaysian Ringgit","RM"],["IDR","Indonesian Rupiah","Rp"],
  ["VND","Vietnamese Dong","₫"],["BND","Brunei Dollar","B$"],["KHR","Cambodian Riel","៛"],["LAK","Lao Kip","₭"],
  ["MMK","Myanmar Kyat","K"],["BDT","Bangladeshi Taka","৳"],["PKR","Pakistani Rupee","₨"],["LKR","Sri Lankan Rupee","Rs"],
  ["NPR","Nepalese Rupee","रू"],["BTN","Bhutanese Ngultrum","Nu"],["MVR","Maldivian Rufiyaa","Rf"],["AFN","Afghan Afghani","؋"],
  ["KZT","Kazakhstani Tenge","₸"],["UZS","Uzbekistani Som","сўм"],["KGS","Kyrgyzstani Som","с"],["TJS","Tajikistani Somoni","SM"],
  ["TMT","Turkmenistani Manat","m"],["MNT","Mongolian Tögrög","₮"],["KPW","North Korean Won","₩"],["MOP","Macanese Pataca","MOP$"],
  ["QAR","Qatari Riyal","﷼"],["KWD","Kuwaiti Dinar","د.ك"],["BHD","Bahraini Dinar",".د.ب"],["OMR","Omani Rial","﷼"],
  ["JOD","Jordanian Dinar","د.ا"],["ILS","Israeli New Shekel","₪"],["LBP","Lebanese Pound","ل.ل"],["SYP","Syrian Pound","£S"],
  ["IQD","Iraqi Dinar","ع.د"],["IRR","Iranian Rial","﷼"],["YER","Yemeni Rial","﷼"],["TRY","Turkish Lira","₺"],
  ["AZN","Azerbaijani Manat","₼"],["GEL","Georgian Lari","₾"],["AMD","Armenian Dram","֏"],
  ["SEK","Swedish Krona","kr"],["NOK","Norwegian Krone","kr"],["DKK","Danish Krone","kr"],["ISK","Icelandic Króna","kr"],
  ["PLN","Polish Złoty","zł"],["CZK","Czech Koruna","Kč"],["HUF","Hungarian Forint","Ft"],["RON","Romanian Leu","lei"],
  ["BGN","Bulgarian Lev","лв"],["RSD","Serbian Dinar","дин"],["MKD","Macedonian Denar","ден"],["ALL","Albanian Lek","L"],
  ["BAM","Bosnian Convertible Mark","КМ"],["MDL","Moldovan Leu","L"],["UAH","Ukrainian Hryvnia","₴"],["BYN","Belarusian Ruble","Br"],
  ["RUB","Russian Ruble","₽"],
  ["MXN","Mexican Peso","Mex$"],["BRL","Brazilian Real","R$"],["ARS","Argentine Peso","AR$"],["CLP","Chilean Peso","CL$"],
  ["COP","Colombian Peso","CO$"],["PEN","Peruvian Sol","S/"],["UYU","Uruguayan Peso","$U"],["PYG","Paraguayan Guaraní","₲"],
  ["BOB","Bolivian Boliviano","Bs"],["VES","Venezuelan Bolívar","Bs.S"],["GYD","Guyanese Dollar","G$"],["SRD","Surinamese Dollar","Sr$"],
  ["GTQ","Guatemalan Quetzal","Q"],["HNL","Honduran Lempira","L"],["NIO","Nicaraguan Córdoba","C$"],["CRC","Costa Rican Colón","₡"],
  ["PAB","Panamanian Balboa","B/."],["DOP","Dominican Peso","RD$"],["CUP","Cuban Peso","$MN"],["JMD","Jamaican Dollar","J$"],
  ["TTD","Trinidad & Tobago Dollar","TT$"],["BBD","Barbadian Dollar","Bds$"],["BSD","Bahamian Dollar","B$"],["BZD","Belize Dollar","BZ$"],
  ["HTG","Haitian Gourde","G"],["XCD","East Caribbean Dollar","EC$"],["AWG","Aruban Florin","ƒ"],["ANG","Netherlands Antillean Guilder","ƒ"],
  ["KYD","Cayman Islands Dollar","CI$"],["BMD","Bermudian Dollar","BD$"],
  ["EGP","Egyptian Pound","E£"],["MAD","Moroccan Dirham","د.م"],["DZD","Algerian Dinar","د.ج"],["TND","Tunisian Dinar","د.ت"],
  ["LYD","Libyan Dinar","ل.د"],["SDG","Sudanese Pound","ج.س"],["ZAR","South African Rand","R"],["NGN","Nigerian Naira","₦"],
  ["GHS","Ghanaian Cedi","₵"],["KES","Kenyan Shilling","KSh"],["TZS","Tanzanian Shilling","TSh"],["UGX","Ugandan Shilling","USh"],
  ["ETB","Ethiopian Birr","Br"],["XOF","West African CFA Franc","CFA"],["XAF","Central African CFA Franc","FCFA"],
  ["RWF","Rwandan Franc","FRw"],["BIF","Burundian Franc","FBu"],["CDF","Congolese Franc","FC"],["ZMW","Zambian Kwacha","ZK"],
  ["MWK","Malawian Kwacha","MK"],["MZN","Mozambican Metical","MT"],["BWP","Botswana Pula","P"],["NAD","Namibian Dollar","N$"],
  ["SZL","Swazi Lilangeni","E"],["LSL","Lesotho Loti","L"],["MUR","Mauritian Rupee","₨"],["SCR","Seychellois Rupee","₨"],
  ["MGA","Malagasy Ariary","Ar"],["AOA","Angolan Kwanza","Kz"],["GMD","Gambian Dalasi","D"],["SLE","Sierra Leonean Leone","Le"],
  ["LRD","Liberian Dollar","L$"],["GNF","Guinean Franc","FG"],["CVE","Cape Verdean Escudo","Esc"],["STN","São Tomé Dobra","Db"],
  ["DJF","Djiboutian Franc","Fdj"],["SOS","Somali Shilling","Sh"],["ERN","Eritrean Nakfa","Nfk"],["KMF","Comorian Franc","CF"],
  ["SSP","South Sudanese Pound","SS£"],["MRU","Mauritanian Ouguiya","UM"],
  ["FJD","Fijian Dollar","FJ$"],["PGK","Papua New Guinean Kina","K"],["SBD","Solomon Islands Dollar","SI$"],["VUV","Vanuatu Vatu","VT"],
  ["WST","Samoan Tālā","WS$"],["TOP","Tongan Paʻanga","T$"],["XPF","CFP Franc","₣"],
  ["GIP","Gibraltar Pound","£"],["FKP","Falkland Islands Pound","£"],["SHP","Saint Helena Pound","£"]
];
